name: Continuous Integration
on: pull_request
jobs:
  integrate:
    name: Integrate changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run format check
        run: pnpm run fmt:check

      - name: Run lint check
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test

      - name: Build library
        run: pnpm run build
