name: Continuous Deployment
on:
  push:
    branches:
      - main
      - alpha
concurrency:
  group: continuous-deployment
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run format check
        run: pnpm run fmt:check

      - name: Run lint check
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test

      - name: Build library
        run: pnpm run build

      - name: Release on NPM
        run: pnpm exec semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
